config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'home/index'

  #Our Session login routes 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :products, :vehicles, :employees, :contracts, 
  :customercontacts, :customernotes, :orders, :order_products, :generate_orders, :routes,
  :load_orders, :customer_portals

  #Custom Routes
  #--------------------------------
  #Customer Custom Routes
  resources :customers do
    get :contacts, on: :member
    
  end

  resources :customers do
    get :notes, on: :member
    
  end
  root 'home#index'
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_secure_password
    #Validation
    validates :Firstname,:Lastname,:Phone,:Email,:Street,:City, 
                presence: true

    #Mapping this object to the Database tables
    self.table_name = "employee"
    self.primary_key = "EmployeeID"
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  #Get all employees from database
  def index
    @employees = Employee.all


    respond_to do |format|
      format.html
      format.pdf do 
          pdf = EmployeePdf.new(@employees)
          send_data pdf.render, filename: "Employee List",
                                type: "application/pdf",
                                disposition: "inline"
          end
      end
  end

  #Show individual Employee
  def show
    @employee = Employee.find(params[:id])
  end

  #New Employee
  def new
    @employee = Employee.new
  end

  #Update an existing Employee
  def edit
    @employee = Employee.find(params[:id])
  end

  #Create a new Employee
  def create
    @employee = Employee.new(employ_params)

    if @employee.save
      redirect_to @employee
    else
      render 'new'
    end
  end
  
  #Update an employee
  def update
    @employee = Employee.find(params[:id])
    
    if @employee.update(employ_params)
      redirect_to @employee
    else
      render 'edit'
    end
  end

  #Delete an Employee
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    
    redirect_to employees_path
  end

  #Define the needed Parameters, A more secure way to send them.
  private
  def employ_params
    params.require(:employee).permit(:EmployeeID, :Firstname, :Lastname,
    :Phone, :Email, :Street, :City, :Province, :Postal, :RoleID, :Active)
  end
  
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, local: true do |form| %>

<% if @employee.errors.any? %>
<div id="error_explanation">
<h2>
    <%= pluralize(@employee.errors.count, "error") %> prohibited
    This employee from being saved:
    </h2>
    <ul>
        <% @employee.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

  <p>
    First Name:
    <%= form.text_field :Firstname %>
  </p>
  
  <p>
    Last Name:
    <%= form.text_field :Lastname %>
  </p>

  <p>
    Phone:
    <%= form.text_field :Phone %>
  </p>

  <p>
    Email:
    <%= form.text_field :Email %>
  </p>

  <p>
    Street:
    <%= form.text_field :Street %>
  </p>

  <p>
    City:
    <%= form.text_field :City %>
  </p>

  <p>
    Province:
    <%= form.select :Province, [ 'AB','BC','MB',
    'NB','NL','NS' 'ON','PE','QC','SK','NT','NU','YT' ], :prompt => 'NB' %>
  </p>

  <p>
    Postal:
    <%= form.text_field :Postal %>
  </p>

  <p>
    Role ID:
    <%= form.select :RoleID, [ 'Accounting','Admin','Dispatcher',
    'Driver','Management','Manager','Sales','Warehouse' ], :prompt => 'Select One' %>
  </p>

  <p>
    Active:
    <%= form.check_box :Active %>
  </p>

  <p>
    Password:
    <%= form.text_field :Password %>
  </p>

  <p>
    <%= form.submit %>
  </p>
  <% end %>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Employees List</h1>

<p><%= link_to 'Back to Main Page', root_path %></p>
<p><%= link_to 'Create New Employee', new_employee_path %></p>
<p><%= link_to "Printable Employees List (PDF)", employees_path(@employees, format: "pdf")  %></p>

<br>

<table>
 <tr>
   <th>Employee ID</th>
   <th>First Name</th>
   <th>Last Name</th>
   <th>Phone</th>
   <th>Email</th>
   <th>Street</th>
   <th>City</th>
   <th>Province</th>
   <th>Postal</th>
   <th>Role ID</th>
   <th>Active</th>
   <th>Password</th>
   
 </tr>

 <% @employees.each do |employee| %>
   <tr>
     <td><%= employee.EmployeeID %></td>
     <td><%= employee.Firstname %></td>
     <td><%= employee.Lastname %></td>
     <td><%= employee.Phone %></td>
     <td><%= employee.Email %></td>
     <td><%= employee.Street %></td>
     <td><%= employee.City %></td>
     <td><%= employee.Province %></td>
     <td><%= employee.Postal %></td>
     <td><%= employee.RoleID %></td>
     <td><%= employee.Active %></td>
     <td><%= employee.Password %></td>

   <td><%= link_to 'Show', employee_path(employee) %></td>
     <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
     <td><%= link_to 'Delete', employee_path(employee),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

   </tr>
 <% end %>
</table>  

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<h1>Employee Information</h1>

<%= link_to 'Back', employees_path %>
<%= link_to 'Edit', edit_employee_path(@employee) %> 

<table>
 <tr>
   <th>Employee ID</th>
   <th>First Name</th>
   <th>Last Name</th>
   <th>Phone</th>
   <th>Email</th>
   <th>Street</th>
   <th>City</th>
   <th>Province</th>
   <th>Postal</th>
   <th>Role ID</th>
   <th>Active</th>
   <th>Password</th>
   
 </tr>

 
   <tr>
     <td><%= @employee.EmployeeID %></td>
     <td><%= @employee.Firstname %></td>
     <td><%= @employee.Lastname %></td>
     <td><%= @employee.Phone %></td>
     <td><%= @employee.Email %></td>
     <td><%= @employee.Street %></td>
     <td><%= @employee.City %></td>
     <td><%= @employee.Province %></td>
     <td><%= @employee.Postal %></td>
     <td><%= @employee.RoleID %></td>
     <td><%= @employee.Active %></td>
     <td><%= @employee.Password %></td>

   </tr>
 
</table>