config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'home/index'

  #Our Session login routes 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :products, :vehicles, :employees, :contracts, 
  :customercontacts, :customernotes, :orders, :order_products, :generate_orders, :routes,
  :load_orders, :customer_portals

  #Custom Routes
  #--------------------------------
  #Customer Custom Routes
  resources :customers do
    get :contacts, on: :member
    
  end

  resources :customers do
    get :notes, on: :member
    
  end
  root 'home#index'
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contract.rb
class Contract < ApplicationRecord

    belongs_to :customer, optional: true, class_name: "Customer", foreign_key: "CustomerID"
    
    has_many :contractproducts, class_name: "ContractProduct", foreign_key: "ContractID"
    has_many :products, :through => :contractproducts 
    has_many :orders, class_name: "Order", foreign_key: "OrderID" 
    #Validation
  
    #Mapping this object to the Database tables
    self.table_name = "contract"
    self.primary_key = "ContractID"

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
    def index
      #@customer = Customer.all
      @contracts = Contract.all
      
    end
    
      #Show individual Contract
      def show
        @contract = Contract.find(params[:id])

        respond_to do |format|
          format.html
          format.pdf do 
              pdf = ContractPdf.new(@contracts)
              send_data pdf.render, filename: "Contract",
                                    type: "application/pdf",
                                    disposition: "inline"
          end
        end

      end
    
#New Contract
def new
  if(params[:customerID])
    #puts "CUSTOMERID " + params[:customerID]
    @contract = Contract.new(CustomerID: params[:customerID])
  else
    @contract = Contract.new
  end
  
end
    
      #Update an existing Contract
      def edit
        @contract = Contract.find(params[:id])
      end
    
      #Create a new Contract
      def create
        @contract = Contract.new(cont_params)
    
        if @contract.save
          redirect_to @contract
        else
          render 'new'
        end
      end
      
      #Update an Contract
      def update
        @contract = Contract.find(params[:id])
        
        if @contract.update(cont_params)
          redirect_to @contract
        else
          render 'edit'
        end
      end
    
      #Delete an Contract
      def destroy
        @contract = Contract.find(params[:id])
        @contract.destroy
        
        redirect_to contracts_path
      end
    
      #Define the needed Parameters, A more secure way to send them.
      private
      def cont_params
        params.require(:contract).permit(:ContractID, :CustomerID, :Discount, :StartDate, :EndDate, 
        :PaymentTerms, :DeliveryDayOfWeek, :EmployeeID, :Note, :Commission, :Active)
      end
  
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<div id= "form">
<%= form_with model: @contract, local: true do |form| %>
 
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contract.errors.count, "error") %> prohibited
        this contract from being saved:
      </h2>
      <ul>
        <% @contract.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    Customer ID:
    <%= form.text_field :CustomerID %>
  </p>
 
  <p>
    Discount:
    <%= form.text_field :Discount %>
  </p>

  <p>
    Start Date:
    <%= date_field(:q, :date, :value => Time.now.strftime('%Y-%m-%d')) %>
  </p>

  <p>
    End Date:
    <%= form.date_select :EndDate %>
  </p>

  <p>
    Payment Terms:
    <%= form.text_field :PaymentTerms %>
  </p>

  <p>
    Delivery Day Of Week:
    <%= form.select :DeliveryDayOfWeek, [ 'Sunday','Monday','Tuesday',
    'Wednesday','Thursday','Friday' 'Saturday' ], :prompt => 'Choose a delivery day' %>
  </p>

  <p>
    Employee ID:
    <%= form.text_field :EmployeeID %>
  </p>

  <p>
    Note:
    <%= form.text_area :Note, size: "30x10" %>
  </p>

  <p>
    Commission:
    <%= form.text_field :Commission %>
  </p>

  <p>
    Active:
    <%= form.check_box :Active %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

</div>

app/views/contracts/edit.html.erb
<h1>Edit Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<h1>Contracts</h1>

<p><%= link_to 'Back to Main Page', root_path %></p>
<p><%= link_to 'Create New contract', new_contract_path %></p>
<br>

<table>
 <tr>
   <th>Contract ID</th>
   <th>Customer ID</th>
   <th>Customer Name</th>
   <th>Delivery Day Of Week</th>
   <th>Note</th>
   <th>Active</th>
   
 </tr>

 <% @contracts.each do |contract| %>
   <tr>
     <td><%= contract.ContractID %></td>
     <td><%= contract.CustomerID %></td>
     <td><%= contract.customer.CustomerName %></td>
     <td><%= contract.DeliveryDayOfWeek %></td>
     <td><%= contract.Note %></td>
     <td><%= contract.Active %></td>
<td><%= link_to 'Show', contract_path(contract) %></td>

   </tr>
 <% end %>
</table>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<h1>contract Information</h1>

<%= link_to 'Back', contracts_path %>
<%= link_to 'Edit', edit_contract_path(@contract) %>
<p><%= link_to "Printable Contract (PDF)", contract_path(@contract, format: "pdf")  %></p>
<br>


<table>
<tr>
<th>Contract Details</th>
</tr>

 <tr>
   <th>Customer ID</th>
   <th>Customer Name</th>
   <th>Discount</th>
   <th>Start Date</th>
   <th>End Date</th>
   <th>Payment Terms</th>
   <th>Delivery Day Of Week</th>
   <th>Employee ID</th>
   <th>Note</th>
   <th>Commission</th>
   <th>Active</th>
   
 </tr>


   <tr>

     <td><%= @contract.CustomerID %></td>
     <td><%= @contract.customer.CustomerName %></td>
     <td><%= @contract.Discount %></td>
     <td><%= @contract.StartDate.strftime('%Y-%A-%B-%d') %></td>
     <td><%= @contract.EndDate.strftime('%Y-%A-%B-%d') %></td>
     <td><%= @contract.PaymentTerms %></td>
     <td><%= @contract.DeliveryDayOfWeek %></td>
     <td><%= @contract.EmployeeID %></td>
     <td><%= @contract.Note %></td>
     <td><%= @contract.Commission %></td>
     <td><%= @contract.Active %></td>

   </tr>
 
</table> 

<br>

<table>
<tr>
<th>Weekly Deliverables</th>
</tr>
 <tr>
   <th>Product ID</th>
   <th>Category</th>
   <th>Pack Size</th>
   <th>SKU</th>
   <th>Price</th>
   
 </tr>
<% @contract.products.each do |product| %>
   <tr>

     <td><%= product.ProductID %></td>
     <td><%= product.Category %></td>
     <td><%= product.PackSize %></td>
     <td><%= product.SKU %></td>
     <td><%= number_to_currency(product.Price) %></td>
   
   </tr>
 <% end %>
</table> 