config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'home/index'

  #Our Session login routes 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :products, :vehicles, :employees, :contracts, 
  :customercontacts, :customernotes, :orders, :order_products, :generate_orders, :routes,
  :load_orders, :customer_portals

  #Custom Routes
  #--------------------------------
  #Customer Custom Routes
  resources :customers do
    get :contacts, on: :member
    
  end

  resources :customers do
    get :notes, on: :member
    
  end
  root 'home#index'
 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    #Validation
    validates :VehicleID,       
                presence: true,
                uniqueness: true,
                numericality: { only_integer: true },
                format: { with: /\A\d+\z/, message: "Integer only. No sign allowed."}  

#Mapping this object to the Database tables
self.table_name = "vehicle"
self.primary_key = "VehicleID"

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

    def index
        @vehicles = Vehicle.all


        respond_to do |format|
            format.html
            format.pdf do 
                pdf = VehiclePdf.new(@vehicles)
                send_data pdf.render, filename: "Vehicles List",
                                      type: "application/pdf",
                                      disposition: "inline"
                end
            end
      end

      def show
        @vehicle = Vehicle.find(params[:id])
      end

    def new
        @vehicle = Vehicle.new
    end

    #Update an existing vehicle
    def edit
        @vehicle = Vehicle.find(params[:id])

    end

    #Create an vehicle
    def create
        @vehicle = Vehicle.new(vehicle_params)

        if @vehicle.save
        redirect_to @vehicle
        else
            render 'new'
        end
    end

    #Update the vehicle
    def update
        @vehicle = Vehicle.find(params[:id])
    
        if @vehicle.update(vehicle_params)
            redirect_to @vehicle
        else
            render 'edit'
        end
    end

    #Delete the vehicle
    def destroy
        @vehicle = Vehicle.find(params[:id])
        @vehicle.destroy
        
        redirect_to vehicles_path

    end

    #private function to collect the parameters
    private
    def vehicle_params
        params.require(:vehicle).permit(:VehicleID, :VehicleDescription,
        :LicensePlate, :Weight, :Capacity)
    end
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/views/vehicles/_form.html.erb
<%= form_with model: @vehicle, local: true do |form| %>
  
   <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@vehicle.errors.count, "error") %> prohibited
        this Vehicle from being saved:
      </h2>
      <ul>
        <% @vehicle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <p>
    Vehicle ID:
    <%= form.text_field :VehicleID %>
  </p>
 
  <p>
    Vehicle Description:
    <%= form.text_field :VehicleDescription %>
  </p>
 
  <p>
    License Plate:
    <%= form.text_field :LicensePlate %>
  </p>

  <p>
    Weight:
    <%= form.text_field :Weight %>
  </p>

  <p>
    Capacity:
    <%= form.text_field :Capacity %>
  </p>


  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Edit Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing Vehicles</h1>

<p><%= link_to 'Back to Main Page', root_path %></p>
<p><%= link_to 'Create New Vehicle', new_vehicle_path %></p>
<p><%= link_to "Printable Vehicles List (PDF)", vehicles_path(@vehicles, format: "pdf")  %></p>


<table>
 <tr>
   <th>Vehicle ID</th>
   <th>Vehicle Description</th>
   <th>License Plate</th>
   <th>Weight</th>
   <th>Capacity</th>

 </tr>

<% @vehicles.each do |vehicle| %>
   <tr>
     <td><%= vehicle.VehicleID %></td>
     <td><%= vehicle.VehicleDescription %></td>
     <td><%= vehicle.LicensePlate %></td>
     <td><%= vehicle.Weight %></td>
     <td><%= vehicle.Capacity %></td>

    <td><%= link_to 'Show', vehicle_path(vehicle) %></td>
    <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
    <td><%= link_to 'Delete', vehicle_path(vehicle),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
   </tr>
 
<% end %>

</table>

app/views/vehicles/new.html.erb
<h1> New Vehicle </h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<h1>Vehicle Information</h1>

<%= link_to 'Back', vehicles_path %>
<%= link_to 'Edit', edit_vehicle_path(@vehicle) %>

<table>
 <tr>
   <th>Vehicle ID</th>
   <th>Vehicle Description</th>
   <th>License Plate</th>
   <th>Weight</th>
   <th>Capacity</th>

 </tr>

   <tr>
     <td><%= @vehicle.VehicleID %></td>
     <td><%= @vehicle.VehicleDescription %></td>
     <td><%= @vehicle.LicensePlate %></td>
     <td><%= @vehicle.Weight %></td>
     <td><%= @vehicle.Capacity %></td>

   </tr>
 
</table>